### PR TITLE
feat: angular 18 stencil integration

### PR DESCRIPTION
**Pull request by stuart-rimel**
### :page_facing_up: Summary of Changes

Adds support for Angular version 18.

Changes include: 
- Create angular output target for ng18
- Adds value accessor bindings for reactive forms compatibility
- Updates theme switcher component to position svgs correctly.
- Updates theme switcher storybook to remove `layout: centered`

Key files:
- `angular-value-acessor-bindings.ts`
- `src/components/molecules/modus-wc-theme-switcher/modus-wc-theme-switcher.tsx`
- `stencil.config.ts`

PRs for publish pipeline and documentation regarding scaffolding integration versions of angular to follow.

### :thought_balloon: Type of Change

- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)
- [ ] Configuration change (modifies scaling or properties of existing infrastructure & services)
- [ ] Documentation change
- [ ] Other

### :clipboard: Test Plan

Manually tested in consumer test angular 18 application.

[demo ng18 app used for testing](https://github.com/stuart-rimel/test-ng18-app)

chrome_JO274Zpxhw

### :white_check_mark: Self Code Review Checklist

PR authors and reviewers, please verify that all of these items have been completed.

- [x] My code is clean and readable
- [x] I followed standard conventions
- [ ] Component code is WCAG 2.2 compliant (if applicable)
- [ ] I have made theme files changes (if applicable)
- [ ] I have made documentation changes (if applicable)
- [ ] I have made Storybook changes including usage documentation (if applicable)
- [ ] I have tested the component thoroughly in Storybook including RTL rendering (if applicable)

### :link: Azure DevOps Work Item

[AB#570779](https://dev.azure.com/ViewpointVSO/74194628-0b6e-4b03-95a4-2d06c069dcbe/_workitems/edit/570779)

### CODE REVIEW

**Comment by stuart-rimel** [comment]
@gabriel-piltzer-trimble @Kai-Richardson 

Currently struggling with getting some styling to work for the angular integration. I have a [test consumer app](https://github.com/stuart-rimel/test-ng18-app) where I use a button and text input component from this branch's stencil angular integration.

In this example, the button seems to have correct styles but the text input component doesn't seem to be consistent with default styling from storybook. For example, I'm noticing a transparent border around the text input in the angular app as shown below. 

chrome_B1tpxPXACT

**Comment by Kai-Richardson** [comment]
> @gabriel-piltzer-trimble @Kai-Richardson
> 
Strange. Have you checked with the browser to see where those styles are coming from?

**Comment by stuart-rimel** [comment]
The `modus-wc-button` component seems to have styling reverted from latest changes #42 

chrome_JEhiGjDxCh

**Comment by stuart-rimel** [comment]
Confirmed styles for updated `modus-wc-badge` component #43 

image

**Review by gabriel-piltzer-trimble — APPROVED** [review]
Overall looks good, nice work.

In the next PR please add internal docs on how to build Angular apps locally, how to publish Angular packages. And update `src/stories/getting-started.mdx` with how to use the Angular integration.

**Pull request merged**
